<?xml version="1.0" encoding="utf-8"?>
<ClassDiagram MajorVersion="1" MinorVersion="1" MembersFormat="FullSignature">
  <Class Name="Autodesk.Revit.ApplicationServices.Application" BaseTypeListCollapsed="true">
    <Position X="5" Y="10.5" Width="8.25" />
    <TypeIdentifier />
    <Lollipop Position="0.2" Collapsed="true" />
  </Class>
  <Class Name="Autodesk.Revit.ApplicationServices.ControlledApplication">
    <Position X="15" Y="10.5" Width="6.75" />
    <TypeIdentifier />
  </Class>
  <Class Name="System.Object">
    <Position X="14.5" Y="5.25" Width="3.25" />
    <TypeIdentifier />
  </Class>
  <Enum Name="Autodesk.Revit.ApplicationServices.LanguageType">
    <Position X="23" Y="10.75" Width="1.75" />
    <TypeIdentifier />
  </Enum>
  <Enum Name="Autodesk.Revit.ApplicationServices.ProductType">
    <Position X="25" Y="10.75" Width="1.5" />
    <TypeIdentifier />
  </Enum>
  <Font Name="Segoe UI" Size="9" />
</ClassDiagram>